name: "Install Valgrind"
description: "Install Homebrew's Valgrind package and cache it."
runs:
  using: "composite"
  steps:
    - run: |
        brew update
        brew tap LouisBrunner/valgrind
        pushd "$(brew --repo LouisBrunner/valgrind)"
        git checkout d14be1d4f76466560ed6515d0f314f0925522456
        popd
        brew install --HEAD LouisBrunner/valgrind/valgrind
      shell: bash
