name: 'Run in Docker with environment'
description: 'Run a command in a Docker container, while passing explicitly set environment variables into the container.'
inputs:
  dockerfile:
    description: 'A Dockerfile that defines an image'
    required: true
  tag:
    description: 'A tag of an image'
    required: true
  command:
    description: 'A command to run in a container'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: myimage
        path: /tmp

    - # Tell Docker to pass environment variables in `env` into the container.
      run: >
        which docker &&
        docker load --input /tmp/myimage.tar &&
        docker run \
          $(echo '${{ toJSON(env) }}' | jq -r 'keys[] | "--env \(.) "') \
          --volume ${{ github.workspace }}:${{ github.workspace }} \
          --workdir ${{ github.workspace }} \
          ${{ inputs.tag }} bash -c "${{ inputs.command }}"
      shell: bash
