include_guard(GLOBAL)

function(generate_pkg_config_file_intermediate in_file)
  set(prefix "@CMAKE_INSTALL_PREFIX@")
  set(exec_prefix "\${prefix}")
  set(libdir "\${exec_prefix}/${CMAKE_INSTALL_LIBDIR}")
  set(includedir "\${prefix}/${CMAKE_INSTALL_INCLUDEDIR}")
  set(PACKAGE_VERSION "${PROJECT_VERSION}")
  configure_file(${in_file} ${PROJECT_NAME}.pc.intermediate @ONLY)
  configure_file(${PROJECT_SOURCE_DIR}/cmake/GeneratePkgConfigFileFinal.cmake.in GeneratePkgConfigFileFinal.cmake @ONLY)
endfunction()
