name: CI
on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  schedule:
    # Run on the default branch every Monday morning.
    # This also warms the Docker caches after key rotation.
    - cron: '22 2 * * 1'

concurrency:
  group: ${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

env:
  ### compiler options
  HOST:
  WRAPPER_CMD:
  # Specific warnings can be disabled with -Wno-error=foo.
  # -pedantic-errors is not equivalent to -Werror=pedantic and thus not implied by -Werror according to the GCC manual.
  WERROR_CFLAGS: '-Werror -pedantic-errors'
  MAKEFLAGS: '-j4'
  BUILD: 'check'
  ### secp256k1 config
  ECMULTWINDOW: 15
  ECMULTGENKB: 86
  ASM: 'no'
  WIDEMUL: 'auto'
  WITH_VALGRIND: 'yes'
  EXTRAFLAGS:
  ### secp256k1 modules
  EXPERIMENTAL: 'no'
  ECDH: 'no'
  RECOVERY: 'no'
  EXTRAKEYS: 'no'
  SCHNORRSIG: 'no'
  MUSIG: 'no'
  ELLSWIFT: 'no'
  ### test options
  SECP256K1_TEST_ITERS: 64
  BENCH: 'yes'
  SECP256K1_BENCH_ITERS: 2
  CTIMETESTS: 'yes'
  SYMBOL_CHECK: 'yes'
  # Compile and run the examples.
  EXAMPLES: 'yes'
  # Disable Docker build summary generation.
  # See https://github.com/docker/build-push-action/blob/master/README.md#environment-variables.
  DOCKER_BUILD_SUMMARY: false

jobs:
  docker_cache:
    name: "Build ${{ matrix.arch }} Docker image"
    runs-on: ${{ matrix.runner }}
    outputs:
      cache_scope: ${{ steps.cache_timestamp.outputs.period }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm

    steps:
      - name: Get cache validity period
        id: cache_timestamp
        run: echo "period=$((10#$(date +%V) / 4))" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          # See: https://github.com/moby/buildkit/issues/3969.
          driver-opts: |
            network=host

      - name: Build container
        uses: docker/build-push-action@v7
        with:
          file: ./ci/linux-debian.Dockerfile
          cache-from: type=gha,scope=${{ runner.arch }}-${{ steps.cache_timestamp.outputs.period }}
          cache-to: type=gha,scope=${{ runner.arch }}-${{ steps.cache_timestamp.outputs.period }},mode=min

  x86_64-debian:
    name: "x86_64: Linux (Debian stable)"
    runs-on: ubuntu-latest
    needs: docker_cache

    strategy:
      fail-fast: false
      matrix:
        configuration:
          - env_vars: { WIDEMUL: 'int64',  RECOVERY: 'yes' }
        cc:
          - 'gcc'

    env:
      CC: ${{ matrix.cc }}

    steps:
      - &CHECKOUT
        name: Checkout
        uses: actions/checkout@v5

      - &CI_SCRIPT_IN_DOCKER
        name: CI script
        env: ${{ matrix.configuration.env_vars }}
        uses: ./.github/actions/run-in-docker-action
        with:
          dockerfile: ./ci/linux-debian.Dockerfile
          scope: ${{ runner.arch }}-${{ needs.docker_cache.outputs.cache_scope }}
          command: ./ci/ci.sh

      - &PRINT_LOGS
        name: Print logs
        uses: ./.github/actions/print-logs
        if: ${{ !cancelled() }}

  x86_64_debian_wheezy:
    name: "x86_64: Linux (Debian Wheezy)"
    runs-on: ubuntu-latest

    env:
      ASM: 'auto'
      WITH_VALGRIND: 'no'
      ECDH: 'yes'
      RECOVERY: 'yes'
      EXTRAKEYS: 'yes'
      SCHNORRSIG: 'yes'
      MUSIG: 'yes'
      ELLSWIFT: 'yes'
      SYMBOL_CHECK: 'no'
      CC: gcc-4.4
      CFLAGS: '-Wno-error=missing-braces -Wno-error=missing-field-initializers -Wno-error=shadow'

    steps:
      - *CHECKOUT

      - name: CI script
        uses: ./.github/actions/run-in-docker-action
        with:
          dockerfile: ./ci/linux-debian7.Dockerfile
          scope: ${{ runner.arch }}
          command: ./ci/ci.sh

      - *PRINT_LOGS
