name: CI Docker image

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'A tag being added to the secp256k1-ci-image Docker image'
        required: true
        type: string
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./ci/linux-debian.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/secp256k1-ci-image:${{ inputs.image_tag }}
