name: CI Docker image

on: [workflow_call, workflow_dispatch]

permissions:
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./ci/linux-debian.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/secp256k1-ci-image:latest
